### ISSUE TITLE
Nested paragraph HTML tags

### ISSUE THREAD

**Issue by wbv** [CHREC/caspr_website#2]
A peek at the source code for the website shows many lines have the following pattern:

```html
<div> <p> <b> ... </b><p> ... </p> </p>
```

Where paragraphs are getting introduced after a label, even though a paragraph is already open.

For example:

```html
<div class="commandlog-caption">
          <p><b>[2022-05-06]: </b><p>Transferred upload to GPU and began unpacking.
Testing new neuromorphic app and scripts.  30-item schedule from SHREC student James uplinked.</p>
</p>
```

Recommending this get addressed even if it doesn't seem to visually break anything.

**Comment by gealy** [comment]
This was a result of Jekyll/Markdown automatically creating a paragraph tag. I have removed my extra paragraph tags surrounding this section. I did not notice this issue as the "Inspect Element" feature of my browser automatically placed the closing paragraph sections, differing from the actual source generated.
